### ISSUE TITLE
Missing link?

### ISSUE THREAD

**Issue by fgfuchs** [danielbultrini/Quantum-Hold-em-#1]
Hi,

Not sure if you are aware, but maybe you could link to https://github.com/sintefmath/QuantumPoker and https://arxiv.org/abs/1908.00044 which predates your code.

Best regards,
Franz

**Comment by danielbultrini** [comment]
Hi Franz!

Of course, there is no problem for us linking to your paper! I wasn't aware
of it, as this was just a hastily thrown together hackathon thing, but it
might be that someone read it while we were working on it.
Although to be fair, the two games have very little to do with each other,
outside of the title, I think. (great paper by the way!)

Best,
Dan

**Comment by fgfuchs** [comment]
Hi Dan,

Thanks for your response. I like your game as well. I will link to this repo from mine.

Best,
Franz
